# Generated by Django 6.0.6 on 2026-07-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('booking', 'New Booking'), ('payment', 'Payment Received'), ('review', 'New Review'), ('contact', 'Contact Message')], default='booking', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, help_text='Relative URL to send admin to on click', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
